// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGh9614hPy8WFcbH4RlCHynrDpm3k-EX8',
    appId: '1:1098658540339:web:4af9a0f121f708a1806c46',
    messagingSenderId: '1098658540339',
    projectId: 'phone-authentication-flutt',
    authDomain: 'phone-authentication-flutt.firebaseapp.com',
    storageBucket: 'phone-authentication-flutt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA698wH4chmypO6fUtSV9lk7E_ZRddZCUY',
    appId: '1:1098658540339:android:844ca44837b31c88806c46',
    messagingSenderId: '1098658540339',
    projectId: 'phone-authentication-flutt',
    storageBucket: 'phone-authentication-flutt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Z1bAwNEm-xbqLf7yGdPi9iCSAAmN8LA',
    appId: '1:1098658540339:ios:424ed05ad7bf6ecc806c46',
    messagingSenderId: '1098658540339',
    projectId: 'phone-authentication-flutt',
    storageBucket: 'phone-authentication-flutt.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Z1bAwNEm-xbqLf7yGdPi9iCSAAmN8LA',
    appId: '1:1098658540339:ios:424ed05ad7bf6ecc806c46',
    messagingSenderId: '1098658540339',
    projectId: 'phone-authentication-flutt',
    storageBucket: 'phone-authentication-flutt.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGh9614hPy8WFcbH4RlCHynrDpm3k-EX8',
    appId: '1:1098658540339:web:1864a73cfd15f6a8806c46',
    messagingSenderId: '1098658540339',
    projectId: 'phone-authentication-flutt',
    authDomain: 'phone-authentication-flutt.firebaseapp.com',
    storageBucket: 'phone-authentication-flutt.appspot.com',
  );
}
